### ISSUE TITLE
Le transfert vers GitLab, est-ce que cela vaut la peine dans l'avenir ? voir description

### ISSUE THREAD

**Issue by mayuba** [UQO-2018-3-INF1583/annotator#12]
Dans le but d'utiliser le pipeline ,le build et transfert vers le serveur automatiquement pour que le projet soit exporté directement dans un environnement de développement et de production.

Cette page explique mieux c'est quoi l'avantage de l'utiliser.
[Lien pipeline gitlab](https://docs.gitlab.com/ee/ci/pipelines.html)

**Comment by levasseurv** [comment]
Ce type d’outils est effectivement intéressant. Cependant, ayant été récemment étudiant, vous comprendrez que l’utilisation d’un nouvel outil demande du temps et que ce temps est particulièrement limité dans le contexte où les étudiants ne travaillent pas exclusivement sur ce projet et sur ce cours. Je ne suggère pas de l’utiliser dans le contexte du cours, à moins que l’ensemble des étudiants ne veuillent l’utiliser.
