### ISSUE TITLE
Demande de confirmation de suppression de projet

### ISSUE THREAD

**Issue by levasseurv** [UQO-2018-3-INF1583/annotator#18]
On peut actuellement supprimer un projet entier en un clic.
Un projet contient des fichiers, des annotateurs, des données de collections (catégories, types, etc) et des annotations. L'impact d'une suppression erronée est important. Il faudrait ajouter un dialogue de confirmation de suppression.

**Comment by mayuba** [comment]
Selon moi, je serai pour mettre le dialogue de confirmation et au lieu de supprimer les données cela va être mieux  d'enlever juste l’indexation vers ce projet.

 Cela peut se faire en déplaçant les données sur une table de données supprimées pour un certain temps puisque l’information c’est une richesse en quelque sorte. Supposons la personne supprime le mauvais projet par erreur il peut demander de la restaurer ou il peut avoir des cas où l’information devient très utile.

**Comment by levasseurv** [comment]
Corrigé dans [5502e93]
