### ISSUE TITLE
Bouton Annotation est présent sans qu'on ajoute un Corpus

### ISSUE THREAD

**Issue by Ensiferus** [UQO-2018-3-INF1583/annotator#35]
### Description
On peut avoir accès à la page d'annotation sans qu'on est sélectionné un corpus en cliquant directement sur le bouton dans la barre de menu.

La page d'annotation devrait être accessible seulement lorsqu'on sélectionne un texte a annoté dans un projet comme le stipule le cahier des charges.

**Comment by Ensiferus** [comment]
En ce moment, il est possible d'aller directement à la page d'annotation lorsqu'on est un utilisateur et qu'on est connecté en effectuant un click gauche sur «Annotation» dans la barre de navigation. 
![image](https://user-images.githubusercontent.com/25160022/49266732-48f84e80-f425-11e8-8cfb-c17f1cd2550e.png)

On arrive alors directement sur une page d'annotation vide.
![image](https://user-images.githubusercontent.com/25160022/49266906-084d0500-f426-11e8-9f57-27e7b78fcbc9.png)

**Comment by Ensiferus** [comment]
### Résolution

Création d'un condition pour afficher seulement «Annotation» lorsqu'un utilisateur est sur une page d'annotation.

![image](https://user-images.githubusercontent.com/25160022/49299121-fa7e9a80-f48c-11e8-97e7-5a98047a3b49.png)

Création d'un style qui fait en sorte qu'il est impossible d'effectuer un click gauche sur «Annotation» dans la barre de navigation.

![image](https://user-images.githubusercontent.com/25160022/49299167-14b87880-f48d-11e8-8723-07fec55e4929.png)

«Annotation» n'est plus disponible dans la barre de navigation.

![image](https://user-images.githubusercontent.com/25160022/49299360-91e3ed80-f48d-11e8-823f-5d66264ccdc8.png)

Il apparait seulement lorsque l'utilisateur est sur une page d'annotation et il n'est pas sélectionnable.

![image](https://user-images.githubusercontent.com/25160022/49299448-c192f580-f48d-11e8-86d8-f18656bdc2b1.png)

**Comment by Ensiferus** [comment]
commit 18483dad82c4c18c9be85f68e4a1d9cb09f7e82e

**Comment by levasseurv** [comment]
Si l'URL est /annotation (sans paramètre) le bouton est affiché et la page d'annotation est vide
