### ISSUE TITLE
Erreur HTTP 404 quand l'usager veut accéder sa page profil lorsqu'il clique sur son username

### ISSUE THREAD

**Issue by dialrahim** [UQO-2018-3-INF1583/annotator#37]
[Devoir 5 Abdoul R. Diallo.docx](https://github.com/UQO-2018-3-INF1583/annotator/files/2644934/Devoir.5.Abdoul.R.Diallo.docx)
L'erreur apparait initialement quand nous cliquons sur le login name de l'utilisateur lorsque celui-ci veut accéder à son profil. Il nous affiche le code d'erreur suivant : HTTP 404. Ce qui veut dire "This page does not exist".
Pour récréer l'erreur, il suffit de suivre les étapes suivantes : 
1- nous accédons au site web: http://localhost:4200
2- À la page principale, nous cliquons sur le login name de l'utilisateur.
![image](https://user-images.githubusercontent.com/16779582/49195737-4da20180-f356-11e8-8e72-438d93a4ce20.png)
3- Il nous affiche l'erreur suivante:
![image](https://user-images.githubusercontent.com/16779582/48795217-2d28d600-ecca-11e8-9a8a-581a7f7e87d3.png)

Au lieu d'avoir cette erreur, celui-ci doit nous amener à une page web qui nous affiche : 
- First name de l'usager.
- Last name de l'usager.
- Email address de l'usager.
- Rôle de l'usager.

C'est un bogue que je considère comme un bogue qui a une sévérité majeure. En effet, il s’agit d’un défaut très grave qui stoppe le déroulement des fonctions. Cependant, certaines parties du système restent fonctionnelles.

**Comment by Bubblesphere** [comment]
Il serait interessant que la page Profile affiche le prénom, le nom et l'adresse courriel. Si tu penses la même chose, tu peux t'inspirer du constructeur du fichier header.component.ts pour récupérer l'information.

![image](https://user-images.githubusercontent.com/8861575/48796364-6151c600-eccd-11e8-9232-9edab331af12.png)

**Comment by dialrahim** [comment]
Le code correspond au commit suivant : 7222fd812396a2fecd6d4918d62cf8a54b20f016
