### ISSUE TITLE
L'option Add est toujours valide même si aucune valeur est entré (tous les objets)

### ISSUE THREAD

**Issue by alexandrebouliane** [UQO-2018-3-INF1583/annotator#45]
Lorsque l'on veut ajouter un objet (Attributs, Entité, Relations, Events) il y a une validation pour chaque information, mais si on clique le + et que l'on clique Add sans rien définir il n'y a aucun message d'erreur. L'objet n'est pas créé mais il n'y a pas de validation pour le Add.

**Comment by mayuba** [comment]
est-ce que c'est possible de mieux expliquer. si possible utiliser une capture d'écran s'il vous plaît.

**Comment by alexandrebouliane** [comment]
bug #45 
Commit : 69a12f61dfb5bc6e94b021bc2e648af1a269e801

**Comment by alexandrebouliane** [comment]
[Rapport Bug_AlexandreBouliane.docx](https://github.com/UQO-2018-3-INF1583/annotator/files/2629515/Rapport.Bug_AlexandreBouliane.docx)
