### ISSUE TITLE
Impossible de se connecter avec un compte Twitter

### ISSUE THREAD

**Issue by avoj02** [UQO-2018-3-INF1583/annotator#54]
### **La Documentation du bug**

**La description du Bug**
Ce n'est pas possible de se connecter à Annotator avec un compte Twitter. Lorsqu'on clique sur l'icône de Twitter rien ne se passe, Normalement on devrait pouvoir se connecter à Annotator  avec nos informations d'authentification Twitter.

**Action pour reproduire le bug**
1.Aller sur la page d'accueil;
2. Cliquer sur le bouton login;
2.Cliquer sur l'icône de Twitter.

**Etat actuel(avant la résolution du bug)**
Lorsqu'on clique sur l'icône de Twitter rien ne se passe , c'est à dire aucune action n'est déclenchée.

**Résultat attendu**
  On doit pouvoir se connecter à Annotator avec un compte Twitter afin d'être conforme au cahier de charge.

### **La correction du bug**
Pour corriger le bug:

1.  J'ai implémenté la fonction signInWithTwitterLogin comme le montre la capture d'écran suivant: 
![c1](https://user-images.githubusercontent.com/43097361/49319069-6566ba80-f4fb-11e8-9f32-e67b07dae13d.PNG)

2. J'ai créé Twitter AuthProvider sur firebase comme le montre la capture d'écran suivant: 
![c3](https://user-images.githubusercontent.com/43097361/49319079-70214f80-f4fb-11e8-9cfd-f67601483f30.PNG)

3. J'ai ajouté l’événement click dans le HTML(component.html) qui permet de charger la page d'authentification de Twitter lorsqu'on clique sur l'icône de Twitter comme le montre la capture d'écran suivant: 
![c2](https://user-images.githubusercontent.com/43097361/49319076-6ac40500-f4fb-11e8-981a-cfe66b134459.PNG)

**Résultat final**
Le bug est résolu.

**Comment by mayuba** [comment]
normalement, il doit être activé dans firebase. veuillez vérifier quand même dans le code s'il est implementer. 
vous pouvez travailler sur les bugs sur la différence quand on s'authentifie avec réseaux sociaux et sans réseau. le rôle n'est pas donné aux usagers qui sont connectés avec les réseaux sociaux et l'un donne un id et l'autre un uid. voir dans la base de données

**Comment by avoj02** [comment]
Bonjour,
J'avais déjà vérifié et il n'est pas implémenté.
Tous les autres réseaux sociaux sont implémentés sauf pour le Twitter.
J'avais déjà eu à discuter avec madame valerie et j'ai donc commencé son implémentation.
Merci et excellente soirée à vous.
Cordialement,
Jonas AVOCE

**Comment by jesutin** [comment]
Le bug est résolu.
La correction est sur ma branch https://github.com/UQO-2018-3-INF1583/annotator/tree/bug%2354_jesutin

**Comment by levasseurv** [comment]
f64e98d
