### ISSUE TITLE
  Il n'y a pas de message d'erreur qui nous demande d'ajouter notre fichier quand on a oublié de le faire pour le Corpus 

### ISSUE THREAD

**Issue by Oswald-Sopi** [UQO-2018-3-INF1583/annotator#56]
Lorsqu'on veut ajouter un nouveau Corpus, il n'ya pas de message d'erreur qui nous demande d'ajouter notre fichier
quand on a oublié de le faire. Juste le titre est obligatoire mais le titre seulen'est pas sauvegardé sans l'ajout du fichier.
l'ajout du fichier devrait etre obligatoire egalement par un message d'alert.

**Comment by Oswald-Sopi** [comment]
Bug #56 #68: Résolu

**Comment by levasseurv** [comment]
d4b92cf
