### ISSUE TITLE
Il est possible de soumettre un fichier vide pour le corpus

### ISSUE THREAD

**Issue by fbl07** [UQO-2018-3-INF1583/annotator#59]
**Descripiton du bug:** Lorsqu'on soummet un fichier pour un nouveau corpus, il est possible de soummettre un fichier vide (taille = 0B).

**Comportement attendu:** Le programme devrait refuser la soumission d'un fichier de taille vide.

**Comment by fbl07** [comment]
Corrigé dans c553fc

**Comment by levasseurv** [comment]
Il est toujours possible de le soumettre, mais il y a un avertissement.
