### ISSUE TITLE
perte de mot de passe 

### ISSUE THREAD

**Issue by zaom01** [UQO-2018-3-INF1583/annotator#61]
absence de restauration du mot de passe en cas de perte

**Comment by mayuba** [comment]
C'est résolu? c'est possible de mettre dans qu'elle commit pour pouvoir retracer les modifications s'il vous plaît

**Comment by mayuba** [comment]
il a des erreurs dans ton commis. c'est possible de le corriger s'il vous plaît
![image](https://user-images.githubusercontent.com/6999749/49387613-48dfa380-f6f0-11e8-8df6-8b930b7a0cd8.png)

**Comment by zaom01** [comment]
j'ai ajouter dans le commit  bf12c75 @mayuba 
es que c'est ce bug @levasseurv ?

**Comment by levasseurv** [comment]
[0d82425]
