### ISSUE TITLE
Les dispositions des cartes changent dans les différents projets 

### ISSUE THREAD

**Issue by reyeh22** [UQO-2018-3-INF1583/annotator#85]
Les dispositions des cartes changent dans les différents projets à cause que les écarts ne sont pas bien définis.   
Projet 1:
![image](https://user-images.githubusercontent.com/25160561/49324580-88df3480-f4fe-11e8-99de-4745e5096edb.png)

Projet 2:
![image](https://user-images.githubusercontent.com/25160561/49324585-98f71400-f4fe-11e8-989f-1acdc7938644.png)
Le scenio attendu est:

![image](https://user-images.githubusercontent.com/25160561/49324591-cc39a300-f4fe-11e8-8ab0-93e9da5da840.png)

**Comment by levasseurv** [comment]
L'écart vertical entre les cartes n'est pas corrigé
